Код изменён в соответствии с требованиями первого задания.
DmitryInd/smart-home-2021 pull request #1
Opened 2021-03-10 23:48 UTC by DmitryInd

2021-03-10 23:48 UTC, DmitryInd commented
Не получилось пригласить @a-ivanov в качестве ревьювера.

2021-03-14 19:07 UTC, a-ivanov requested changes

2021-03-14 19:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/JsonSmartHomeRecorder.java
> +    public SmartHome getSmartHome() {
Лучше read/load, get - это когда возвращают ссылку на уже существующий объект в памяти.

2021-03-14 19:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/SmartHomeReceiverEvents.java
> +    private SmartHome smartHome;
Поля лучше располагать сверху, перед конструктором.

2021-03-14 19:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/SmartHomeReceiverEvents.java
> +            if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
OCP: перепишите код так, чтобы можно было добавлять новые обработчики без изменения этого класса.

2021-03-14 19:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/SmartHomeReceiverEvents.java
> +                handler = new LightSmartHomeHandler(smartHome, output);
DIP: передайте сюда список из `SmartHomeHandler`, созданные в `main`, не создавайте новые инстансы обработчиков.

2021-03-14 19:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/DoorSmartHomeHandler.java
> +            if (event.getType() == DOOR_CLOSED && currentRoom.getName().equals("hall")) {
SRP: отдельный обработчик для сценариев.

2021-03-14 19:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/DoorSmartHomeHandler.java
> +    private Room currentRoom = null;
Лучше сделать локальной переменной.

2021-03-14 19:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/SmartHomeHandler.java
> +public abstract class SmartHomeHandler implements Handler {
Не стоит создавать абстрактный класс ради полей. В классе много ограничений. Переделайте в интерфейс.

2021-03-14 20:25 UTC, DmitryInd commented on src/main/java/ru/sbt/mipt/oop/events/SmartHomeReceiverEvents.java
> +                handler = new LightSmartHomeHandler(smartHome, output);
А достаточно будет передавать HashMap<EventType, SmartHomeHandler> (тут нужно учитывать, что на один handler может быть несколько EventType), или нужно, чтобы все Handler-ы запускались подряд, а внутри них уже проходили проверки на тип события?

2021-03-14 20:27 UTC, DmitryInd commented on src/main/java/ru/sbt/mipt/oop/events/DoorSmartHomeHandler.java
> +            if (event.getType() == DOOR_CLOSED && currentRoom.getName().equals("hall")) {
Не очень понимаю, тут же и так создаётся и используется отдельный класс сценария для того, чтобы у обработчика оставалась только одна причина для изменений - перетасовка действий при закрытии двери.

2021-03-17 15:20 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/SmartHomeReceiverEvents.java
> +                handler = new LightSmartHomeHandler(smartHome, output);
Сейчас предлагаю остановиться на втором более простом решении (со списком).

2021-03-17 15:22 UTC, a-ivanov approved these changes

2021-03-17 20:04 UTC, merged