Второе задание
DmitryInd/smart-home-2021 pull request #2
Opened 2021-03-18 01:15 UTC by DmitryInd

2021-03-19 06:44 UTC, a-ivanov reviewed
Удалите все методы с доступом к внутренним данным объектов.

2021-03-19 06:44 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/iterators/RoomInternalIterator.java
> +public class RoomInternalIterator implements InternalIterator {
Это не внутренний итератор. Внутренний итератор - это Actionable + Action. Удалите этот класс (и ему подобные), он просто дублирует логику for each цикла.

2021-03-19 06:44 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/SmartHomeAction.java
> +    void performOn(SmartHomeObject object);
Ограничение аргумента маркерным интерфейсом - хороший подход.

2021-03-19 06:44 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/GetDoorRoomSmartHomeAction.java
> +                roomName.delete(0, roomName.length());
Просто переприсваивайте ссылку на новое имя в поле (либо локальную переменную), не надо модифицировать строки. Они immutable, это дорогая операция.

2021-03-19 06:44 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/SmartHome.java
> +    public void addRoom(Room room) { rooms.add(room); }
Удалите.

2021-03-19 06:45 UTC, a-ivanov requested changes
Исправьте.

2021-03-19 09:14 UTC, DmitryInd commented on src/main/java/ru/sbt/mipt/oop/actions/GetDoorRoomSmartHomeAction.java
> +                roomName.delete(0, roomName.length());
@a-ivanov, не совсем понял, что нужно сделать. Последняя операция проводится только один раз, когда action применяется на нужной двери, в остальных комнатах, как раз переприсваивается ссылка в currentRoom на имя текущей комнаты.

2021-03-19 09:37 UTC, DmitryInd commented on src/main/java/ru/sbt/mipt/oop/actions/SmartHomeAction.java
> +    void performOn(SmartHomeObject object);
@a-ivanov, не понял, что требуется сделать.

2021-03-22 05:47 UTC, a-ivanov requested changes

2021-03-22 05:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/SmartHome.java
> +        rooms.iterator().forEachRemaining(room -> room.execute(smartHomeAction));
Зачем вручную вызывать iterator? Просто используйте for (Room room : rooms) или rooms.forEach(room ->...).

2021-03-22 05:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/MoveDoorSmartHomeAction.java
> +    public MoveDoorSmartHomeAction(boolean isToOpen, String id, OutputStream output) {
Непонятное название, здесь, судя по коду, происходит закрытие двери.

2021-03-22 05:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/TurnOffAllLightsSmartHomeAction.java
> +            SenderCommands senderCommands = new DummySenderCommands();
Нарушение DIP, передавайте отправителя команд через конструктор.

2021-03-23 16:13 UTC, a-ivanov approved these changes

2021-03-23 16:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/EntranceSmartHomeHandler.java
> +            smartHome.execute(new TurnOffAllLightsSmartHomeAction(new DummySenderCommands()));
Ну dummysendercommand можно создать один раз в main и передавать из поля в команду, а не каждый раз заново создавать.

2021-03-23 16:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/pointer/Pointer.java
> +public class Pointer<T> {
Зачем? Чем не устраивает просто ссылка на объект (переменная)?

2021-03-23 16:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/SmartHome.java
> +    public void execute(SmartHomeAction smartHomeAction) {
Можно ещё дом добавить.

2021-03-23 16:20 UTC, DmitryInd commented on src/main/java/ru/sbt/mipt/oop/pointer/Pointer.java
> +public class Pointer<T> {
@a-ivanov, потому что мне нужно, чтобы значение было получено вне action: handler должен узнать, где была закрыта дверь. А при изменении String меняется ссылка на объект, то есть значение, хранящееся в handler (вне action) остаётся прежним.

2021-03-23 16:22 UTC, DmitryInd commented on src/main/java/ru/sbt/mipt/oop/smarthome/SmartHome.java
> +    public void execute(SmartHomeAction smartHomeAction) {
@a-ivanov, зачем?

2021-03-23 16:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/pointer/Pointer.java
> +public class Pointer<T> {
Можно добавить поле в класс действия. Либо (более хороший вариант) вообще обойтись без мутабельных реализаций действий. Можно просто проходиться по дому, искать дверь, проверять, если ид закрытия совпадает с дверью ч именем холла, то запускать в доме выключение света. И не нужны никакие указатели.

2021-03-23 16:25 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/SmartHome.java
> +    public void execute(SmartHomeAction smartHomeAction) {
Потому, что он тоже Actionable, и, возможно, кто-то захочет написать для него обработчик.

2021-03-23 16:34 UTC, DmitryInd commented on src/main/java/ru/sbt/mipt/oop/smarthome/SmartHome.java
> +    public void execute(SmartHomeAction smartHomeAction) {
@a-ivanov, вероятно я не очень понимаю, куда именно нужно добавить дом

2021-03-23 16:40 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/SmartHome.java
> +    public void execute(SmartHomeAction smartHomeAction) {
`action.apply(this)`, потом дом применяет действие к комнатам.

2021-03-24 21:51 UTC, merged